# Generated by Django 4.0.4 on 2022-05-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
